version: 0.2
env:
  variables:
    TEST_VARIABLE: "test_value"
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo `pwd`
      - sbt sbtVersion
  build:
    commands:
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - echo $CODEBUILD_SOURCE_VERSION
      - printenv
      - sbt clean server/Universal/stage
artifacts:
  files:
    - '**/*'
  base-directory: server/target/universal/stage
